// Generated by CoffeeScript 1.6.2
(function() {
  var Curtain;

  Curtain = (function() {
    function Curtain(o) {
      this.o = o != null ? o : {};
      this.vars();
      this.rotate();
    }

    Curtain.prototype.vars = function() {
      this.$image1 = $('#curtain-image1');
      this.$image2 = $('#curtain-image2');
      return this.animate = StatSocial.helpers.bind(this.animate, this);
    };

    Curtain.prototype.rotate = function() {};

    Curtain.prototype.animate = function() {
      requestAnimationFrame(this.animate);
      return TWEEN.update();
    };

    return Curtain;

  })();

  new Curtain;

}).call(this);

/*
//@ sourceMappingURL=curtain.map
*/
