// Generated by CoffeeScript 1.6.2
(function() {
  var Helpers, _ref;

  Helpers = (function() {
    function Helpers() {}

    Helpers.prototype.bind = function(func, context) {
      var bindArgs, wrapper;

      wrapper = function() {
        var args, unshiftArgs;

        args = Array.prototype.slice.call(arguments);
        unshiftArgs = bindArgs.concat(args);
        return func.apply(context, unshiftArgs);
      };
      bindArgs = Array.prototype.slice.call(arguments, 2);
      return wrapper;
    };

    Helpers.prototype.extend = function(obj, obj2) {
      var key, value;

      for (key in obj2) {
        value = obj2[key];
        if (obj2[key] != null) {
          obj[key] = value;
        }
      }
      return obj;
    };

    Helpers.prototype.getRand = function(min, max) {
      return Math.floor((Math.random() * ((max + 1) - min)) + min);
    };

    Helpers.prototype.isIE = function() {
      var msie, rv, rvNum, trident, ua, undef;

      if (this.isIECache) {
        return this.isIECache;
      }
      undef = void 0;
      rv = -1;
      ua = window.navigator.userAgent;
      msie = ua.indexOf("MSIE ");
      trident = ua.indexOf("Trident/");
      if (msie > 0) {
        rv = parseInt(ua.substring(msie + 5, ua.indexOf(".", msie)), 10);
      } else if (trident > 0) {
        rvNum = ua.indexOf("rv:");
        rv = parseInt(ua.substring(rvNum + 3, ua.indexOf(".", rvNum)), 10);
      }
      this.isIECache = (rv > -1 ? rv : undef);
      return this.isIECache;
    };

    return Helpers;

  })();

  if ((_ref = window.StatSocial) == null) {
    window.StatSocial = {};
  }

  window.StatSocial.helpers = new Helpers;

}).call(this);

/*
//@ sourceMappingURL=helpers.map
*/
