// Generated by CoffeeScript 1.6.2
(function() {
  var App;

  App = (function() {
    function App() {
      this.vars();
      this.initScroll();
    }

    App.prototype.vars = function() {
      this.$main = $('#js-main');
      return this.scrollPos = 0;
    };

    App.prototype.initScroll = function() {
      console.log(this.$main[0]);
      this.scroller = new IScroll('#js-main', {
        probeType: 3,
        mouseWheel: true
      });
      document.addEventListener('touchmove', (function(e) {
        return e.preventDefault();
      }), false);
      this.scroller.on('scroll', this.updateScrollPos);
      return this.scroller.on('scrollEnd', this.updateScrollPos);
    };

    App.prototype.updateScrollPos = function() {
      return console.log(this.y >> 0);
    };

    return App;

  })();

  new App;

}).call(this);

/*
//@ sourceMappingURL=main.map
*/
