// Generated by CoffeeScript 1.6.2
(function() {
  var Point;

  Point = (function() {
    function Point(o) {
      this.o = o != null ? o : {};
    }

    return Point;

  })();

  window.StatSocial.RollerPoint = Point;

}).call(this);

/*
//@ sourceMappingURL=point.map
*/
