// Generated by CoffeeScript 1.6.2
(function() {
  var Roller;

  Roller = (function() {
    Roller.prototype.endPoints1 = [];

    Roller.prototype.endPoints2 = [];

    function Roller(o) {
      this.o = o != null ? o : {};
      this.vars();
      this.showAxes();
    }

    Roller.prototype.vars = function() {
      this.$rollerLine1 = $('#roller-line1');
      this.$rollerLine2 = $('#roller-line2');
      this.$x = $('#roller-x');
      return this.$y = $('#roller-y');
    };

    Roller.prototype.showAxes = function() {
      var yEnd;

      return yEnd = parseInt(this.$y.attr('transform').split(',')[1], 10);
    };

    return Roller;

  })();

  new Roller;

}).call(this);

/*
//@ sourceMappingURL=roller-coaster.map
*/
